package com.revature.soap;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2018-04-11T10:46:05.082-04:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "HeroGreetingService", 
                  wsdlLocation = "http://localhost:8085/SOAPService/heroGreeting?wsdl",
                  targetNamespace = "http://soap.revature.com/") 
public class HeroGreetingService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://soap.revature.com/", "HeroGreetingService");
    public final static QName HeroGreetingAlphaPort = new QName("http://soap.revature.com/", "HeroGreetingAlphaPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8085/SOAPService/heroGreeting?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HeroGreetingService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://localhost:8085/SOAPService/heroGreeting?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HeroGreetingService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HeroGreetingService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HeroGreetingService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public HeroGreetingService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public HeroGreetingService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public HeroGreetingService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns HeroGreeting
     */
    @WebEndpoint(name = "HeroGreetingAlphaPort")
    public HeroGreeting getHeroGreetingAlphaPort() {
        return super.getPort(HeroGreetingAlphaPort, HeroGreeting.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HeroGreeting
     */
    @WebEndpoint(name = "HeroGreetingAlphaPort")
    public HeroGreeting getHeroGreetingAlphaPort(WebServiceFeature... features) {
        return super.getPort(HeroGreetingAlphaPort, HeroGreeting.class, features);
    }

}
